version: 2.1
jobs:
  test:
    docker:
    - image: cypress/included:3.3.1
    steps:
    - checkout
    - run:
        name: Cypress tests
        command: cypress run
workflows:
  build:
    jobs:
    - test
  version: 2
